fix: Add missing react-is dependency for Recharts
Added react-is package to resolve dependency error when running frontend dev server.

Error: Could not resolve 'react-is' from node_modules/recharts/es6/util/ReactUtils.js

This is required by Recharts for React component type checking.